// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var ReactNativeFontawesome = require("react-native-fontawesome");

var component = ReasonReact.statelessComponent("Icon");

function make() {
  return ReasonReact.wrapJsForReason(ReactNativeFontawesome.default, { }, ReactNativeFontawesome.Icons.trash);
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
