// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var View$BsReactNative = require("bs-react-native/lib/js/src/components/view.js");
var Style$BsReactNative = require("bs-react-native/lib/js/src/style.js");
var TextInput$BsReactNative = require("bs-react-native/lib/js/src/components/textInput.js");
var StyleSheet$BsReactNative = require("bs-react-native/lib/js/src/styleSheet.js");

var component = ReasonReact.reducerComponent("Input");

function make(_, onSubmit) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (param) {
      var send = param[/* send */4];
      var text = param[/* state */2];
      var handleSubmit = function () {
        Curry._1(onSubmit, text);
        return Curry._1(send, " ");
      };
      var handleChange = Curry.__1(send);
      var styles = StyleSheet$BsReactNative.create({
            input: Style$BsReactNative.style(/* :: */[
                  Style$BsReactNative.backgroundColor("#0003"),
                  /* :: */[
                    Style$BsReactNative.fontSize(/* Float */Block.__(0, [18])),
                    /* :: */[
                      Style$BsReactNative.borderRadius(25),
                      /* :: */[
                        Style$BsReactNative.padding(/* Pt */Block.__(0, [5])),
                        /* :: */[
                          Style$BsReactNative.textAlign(/* Center */3),
                          /* :: */[
                            Style$BsReactNative.width(/* Pct */Block.__(1, [60])),
                            /* :: */[
                              Style$BsReactNative.marginLeft(/* Auto */0),
                              /* :: */[
                                Style$BsReactNative.marginRight(/* Auto */0),
                                /* :: */[
                                  Style$BsReactNative.marginTop(/* Pt */Block.__(0, [-40])),
                                  /* :: */[
                                    Style$BsReactNative.color("#f9f9f9"),
                                    /* [] */0
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ])
          });
      return ReasonReact.element(/* None */0, /* None */0, View$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[ReasonReact.element(/* None */0, /* None */0, TextInput$BsReactNative.make(/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[styles.input], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[/* false */0], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */[handleSubmit], /* None */0, /* Some */[handleChange], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */["Add a todo..."], /* Some */["#f9f9f9"], /* None */0, /* None */0, /* None */0, /* None */0, /* Some */["#f9f9f9"], /* Some */[text], /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0)(/* array */[]))]));
    });
  newrecord[/* initialState */10] = (function () {
      return "";
    });
  newrecord[/* reducer */12] = (function (newText, _) {
      return /* Update */Block.__(0, [newText]);
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
